version: 2.1

orbs:
  android: circleci/android@2.5.0
  gh: circleci/github-cli@2.3.0
  github-app-token: ostk0069/github-app-token@0.0.1

parameters:
  target-branch:
    description: "PR先のbranch"
    type: string
    default: ""
  pr-number:
    description: "PRの番号"
    type: integer
    default: 0

commands:
  setup-siging-debug:
    description: "Debug用のsigingのsetup"
    steps:
      - run:
          name: siging.properties
          command: |
            touch siging.properties
            echo $SIGING_PROPERTIES | base64 -d >> siging.properties
      - run:
          name: debug.jks
          command: |
            touch debug.jks
            echo $DEBUG_JKS | base64 -d >> debug.jks
  setup-siging-release:
    description: "Release用のsigingのsetup"
    steps:
      - run:
          name: siging.properties
          command: |
            touch siging.properties
            echo $SIGING_PROPERTIES | base64 -d >> siging.properties
      - run:
          name: release.jks
          command: |
            touch release.jks
            echo $RELEASE_JKS | base64 -d >> release.jks
  setup-local-properties:
    description: "local.propertiesのsetup(Empty)"
    steps:
      - run:
          name: local.properties
          command:
            touch local.properties
  setup-debug-google-services:
    description: "Debug用のgoogle-services.jsonのsetup"
    steps:
      - run:
          name: google-services.json
          command: |
            touch ./app/src/debug/google-services.json
            echo $DEBUG_SERVICE_JSON | base64 -d >> ./app/src/debug/google-services.json
  setup-release-google-services:
    description: "Release用のgoogle-services.jsonのsetup"
    steps:
      - run:
          name: google-services.json
          command: |
            touch ./app/src/release/google-services.json
            echo $RELEASE_SERVICE_JSON | base64 -d >> ./app/src/release/google-services.json


jobs:
  lint:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run:
          name: chmod gradlew
          command: |
            chmod +x gradlew
      - setup-local-properties
      - setup-siging-debug
      - setup-debug-google-services
      - run:
          name: detekt
          command: |
            ./gradlew detekt --auto-correct
  release-build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: chmod gradlew
          command: |
            chmod +x gradlew
      - setup-local-properties
      - setup-siging-release
      - setup-release-google-services
      - run:
          name: build
          command: |
            ./gradlew assembleRelease
      - android/save-gradle-cache
      - android/save-build-cache
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - android/restore-gradle-cache
      - run:
          name: chmod gradlew
          command: |
            chmod +x gradlew
      - setup-local-properties
      - setup-siging-debug
      - setup-debug-google-services
      - run:
          name: build
          command: |
            ./gradlew assembleDebug --stacktrace
          no_output_timeout: 20m
      - android/save-gradle-cache
  unittest:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: chmod gradlew
          command: |
            chmod +x gradlew
      - setup-local-properties
      - setup-siging-debug
      - setup-debug-google-services
      - run:
          name: UnitTest
          command: |
            ./gradlew testDebugUnitTest
      - android/save-gradle-cache
      - android/save-build-cache
  save-screenshot:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run:
          name: chmod gradlew
          command: |
            chmod +x gradlew
      - setup-local-properties
      - setup-siging-debug
      - setup-debug-google-services
      - run:
          name: take screenshot
          command: |
            ./gradlew recordRoborazziDebug --stacktrace
          no_output_timeout: 20m
      - store_artifacts:
          path: app/build/outputs/roborazzi
  screen-shot:
    parameters:
      target-branch:
        type: string
        default: ""
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run:
          name: checkout target branch
          command: |
            git checkout <<parameters.target-branch>>
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: chmod gradlew
          command: |
            chmod +x gradlew
      - setup-local-properties
      - setup-siging-debug
      - setup-debug-google-services
      - run:
          name: take screenshot
          command: |
            ./gradlew recordRoborazziDebug --stacktrace
          no_output_timeout: 20m
      - persist_to_workspace:
          root: ./app/build/outputs/roborazzi
          paths:
            - .
  vrt:
    parameters:
      target-branch:
        type: string
        default: ""
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - attach_workspace:
          at: ./app/build/outputs/roborazzi
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: chmod gradlew
          command: |
            chmod +x gradlew
      - setup-local-properties
      - setup-siging-debug
      - setup-debug-google-services
      - run:
          name: compare screenshot
          no_output_timeout: 30m
          command: |
            ./gradlew compareRoborazziDebug --stacktrace
      - android/save-gradle-cache
      - android/save-build-cache
      - run:
          name: delete unnecessary files
          command: |
            find app/build/outputs/roborazzi -mindepth 1 -maxdepth 1 ! -name '*_compare.png' -exec rm -r {} +
      - store_artifacts:
          path: app/build/outputs/roborazzi
      - run:
          name: create result json file
          command: |
            curl -H "Circle-Token: $CIRCLE_TOKEN" "https://circleci.com/api/v2/project/github/SnowDango/sumire/$CIRCLE_BUILD_NUM/artifacts" --output artifact.json
            cat artifact.json
      - persist_to_workspace:
          root: ./
          paths:
            - artifact.json
  result-comment:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - gh/install
      - attach_workspace:
          at: ./
      - run:
          name: create comment
          command: |
            sh create-comment.sh
      - github-app-token/fetch-token:
          app_id: $GITHUB_APPS_ID
          base64_private_key: $GITHUB_APPS_PRIVATE_KEY
          installation_id: 54651436
      - run:
          name: pull request comment
          command: |
            echo "$GITHUB_APP_TOKEN" | gh auth login --with-token
            comments=$(gh pr view "$CIRCLE_PULL_REQUEST" --comments --json comments --jq '[.comments[].author.login]|any(.=="sumire-apps")')
            echo $comments
            if [ ${comments} = "true" ]; then
              gh pr comment "$CIRCLE_PULL_REQUEST" -F comment.txt --edit-last
            else
              gh pr comment "$CIRCLE_PULL_REQUEST" -F comment.txt
            fi
workflows:
  save-screenshot:
    jobs:
      - save-screenshot:
          filters:
            branches:
              only:
                - "develop"
                - "master"
  release-build-test:
    jobs:
      - release-build:
          filters:
            branches:
              only:
                - "develop"
  build-test:
    jobs:
      - lint:
          filters:
            branches:
              ignore:
                - "master"
      - build:
          requires:
            - lint
      - unittest:
          requires:
            - build
  vrt-test:
    when:
      not:
        equal: [ "", << pipeline.parameters.target-branch >> ]
    jobs:
      - screen-shot:
          target-branch: << pipeline.parameters.target-branch >>
      - vrt:
          target-branch: << pipeline.parameters.target-branch >>
          requires:
            - screen-shot
      - result-comment:
          requires:
            - vrt

