version: 2.1

orbs:
  android: circleci/android@2.5.0
  gh: circleci/github-cli@2.3.0

parameters:
  target-branch:
    description: "PR先のbranch"
    type: string
    default: ""
  pr-number:
    description: "PRの番号"
    type: integer
    default: 0

jobs:
  save-screenshot:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run:
          name: chmod gradlew
          command: |
            chmod +x gradlew
      - run:
          name: take screenshot
          command: |
            ./gradlew recordRoborazziDebug --stacktrace
      - store_artifacts:
          path: app/build/outputs/roborazzi
  vrt-test:
    parameters:
      target-branch:
        type: string
        default: ""
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run:
          name: get artifacts
          command: |
            mkdir -p app/build/outputs/roborazzi | \
            curl -H "Circle-Token: $CIRCLE_TOKEN" "https://circleci.com/api/v1.1/project/github/SnowDango/sumire/latest/artifacts?branch=<<parameters.target-branch>>&filter=completed" | \
            jq -c '.[]' | while read artifact; do
              curl -H "Circle-Token: $CIRCLE_TOKEN" -L "$(echo $artifact | jq -r '.url')?circle-token=$CIRCLE_TOKEN" --output "$(echo $artifact | jq -r '.path')"
            done
      - run:
          name: chmod gradlew
          command: |
            chmod +x gradlew
      - run:
          name: compare screenshot
          command: |
            ./gradlew compareRoborazziDebug --stacktrace
      - run:
          name: delete unnecessary files
          command: |
            ls app/build/outputs/roborazzi | grep -v -E "*_compare.png" | xargs rm -rf
      - store_artifacts:
          path: app/build/outputs/roborazzi
  result-comment:
    parameters:
      pr-number:
        type: integer
        default: 0
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gh/install
      - run:
          name: create comment
          command: |
            echo "VRT Result" > comment
            echo "| image |" >> comment
            echo "|-------|" >> comment
            curl -H "Circle-Token: $CIRCLE_TOKEN" "https://circleci.com/api/v2/project/github/SnowDango/sumire/$CIRCLE_BUILD_NUM/artifacts" | \
            jq -c '.[]' | while read artifact; do
              echo "| ![]($(echo $artifact | jq -r '.url')) |" >> comment
            done
      - run:
          name: pull request comment
          command: |
            echo "$GITHUB_ACCESS_TOKEN" | gh auth login --with-token
            gh pr comment $pr-number -b "$comment"
workflows:
  save-screenshot:
    jobs:
      - save-screenshot:
          filters:
            branches:
              only:
                - "develop"
                - "master"
  vrt-test:
    when:
      not:
        equal: [ "", << pipeline.parameters.target-branch >> ]
    jobs:
      - vrt-test:
          target-branch: << pipeline.parameters.target-branch >>
      - result-comment:
          pr-number: << pipeline.parameters.pr-number >>

