version: 2.1

orbs:
  android: circleci/android@2.5.0

parameters:
  target-branch:
    description: "PR先のbranch"
    type: string
    default: ""

jobs:
  save-screenshot:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run:
          name: chmod gradlew
          command: |
            chmod +x gradlew
      - run:
          name: take screenshot
          command: |
            ./gradlew recordRoborazziDebug --stacktrace
      - store_artifacts:
          path: app/build/outputs/roborazzi
  vrt-test:
    parameters:
      target-branch:
        type: string
        default: ""
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run:
      - run:
          name: get artifacts
          command: |
            mkdir -p app/build/outputs/roborazzi \
            artifacts=$(curl -H "Circle-Token: $CIRCLE_TOKEN" "https://circleci.com/api/v1.1/project/github/SnowDango/sumire/latest/artifacts?branch=<<parameters.target-branch>>&filter=completed") \
            for artifact in $(echo $artifact | jq -c '.[]'); do curl -o app/build/outputs/roborazzi $(echo $artifact | jq -r '.url') done
      - run:
          name: chmod gradlew
          command: |
            chmod +x gradlew
      - run:
          name: compare screenshot
          command: |
            ./gradlew compareRoborazziDebug --stacktrace
      - store_artifacts:
          path: app/build/outputs/roborazzi


workflows:
  save-screenshot:
    jobs:
      - save-screenshot:
          filters:
            branches:
              only:
                - "develop"
                - "master"
  vrt-test:
    when:
      not:
        equal: [ "", << pipeline.parameters.target-branch >> ]
    jobs:
      - vrt-test:
          target-branch: << pipeline.parameters.target-branch >>
