version: 2.1

orbs:
  android: circleci/android@2.5.0

jobs:
  save-screenshot:
    executor:
      name: android/android-machine
      resource-class: large
      tag: default
    steps:
      - checkout
      - run:
          name: chmod gradlew
          command: |
            chmod +x gradlew
      - run:
          name: take screenshot
          command: |
            ./gradlew recordRoborazziDebug --stacktrace
      - store_artifacts:
          path: app/build/outputs/roborazzi

workflows:
  save-screenshot:
    jobs:
      - save-screenshot:
          filters:
            branches:
              only:
                - "develop"
                - "master"