version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  save-screenshot:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - run:
          name: take screenshot
          command: |
            ./gradlew recordRoborazziDebug --stacktrace
      - store_artifacts:
          path: app/build/outputs/roborazzi

workflows:
  save-screenshot:
    jobs:
      - save-screenshot:
          filters:
            branches:
              only:
                - "develop"
                - "master"