name: CompareScreenshot

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  compare-screenshot-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read # for clone
      actions: write # for upload-artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          name: screenshot
          workflow: UnitTest.yml
          branch: develop
      - run: ./gradlew compareRoborazziDebug --stacktrace
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot-diff
          path: |
            **/build/outputs/roborazzi
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshot-diff-reports
          path: |
            **/build/outputs/roborazzi
          retention-days: 30
      - name: Save PR number
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v4
        with:
          name: pr
          path: pr/