name: Debug Upload DeployGate

on:
  push:
    branches:
      - develop
jobs:
  debug-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: chmod gradlew
        run: |
          chmod +x gradlew
      - name: create local.properties
        run: |
          touch local.properties
          echo "deploygate.user=${{ secrets.DEPLOYGATE_USER }}" >> local.properties
          echo "deploygate.token=${{ secrets.DEPLOYGATE_TOKEN }}" >> local.properties
      - name: build debug
        run:
          ./gradlew assembleDebug
      - name: deploy debug
        run:
          ./gradlew uploadDeployGateDebug
