name: Release Upload DeployGate

on:
  push:
    branches:
      - master
jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: chmod gradlew
        run: |
          chmod +x gradlew
      - name: create local.properties
        run: |
          touch local.properties
      - name: create siging.properties
        run: |
          touch siging.properties
          echo "${{ secrets.SIGING_PROPERTIES }}" | base64 -d >> siging.properties
      - name: create release.jks
        run: |
          touch release.jks
          echo "${{ secrets.RELEASE_JKS }}" | base64 -d >> release.jks
      - name: build release
        run:
          ./gradlew assembleRelease
      - name: deploy release
        run:
          ./gradlew uploadDeployGateRelease
