name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

permissions:
  contents: write
  discussions: write

jobs:
  prod-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: chmod gradlew
        run: |
          chmod +x gradlew
      - name: create local.properties
        run: |
          touch local.properties
      - name: create siging.properties
        run: |
          touch siging.properties
          echo "${{ secrets.SIGING_PROPERTIES }}" | base64 -d >> siging.properties
      - name: create release.jks
        run: |
          touch release.jks
          echo "${{ secrets.RELEASE_JKS }}" | base64 -d >> release.jks
      - name: create google-services.json
        run:
          touch ./app/src/release/google-services.json
          echo "${{ secrets.RELEASE_SERVICE_JSON }}" | base64 -d >> ./app/src/release/google-services.json
      - name: build release apk
        run:
          ./gradlew assembleRelease --no-daemon
      - name: build release aab
        run:
          ./gradlew bundleRelease --no-daemon
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.event.inputs.tag }}
          body: ${{ github.event.inputs.tag }}
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            ./app/build/outputs/apk/release/app-release.apk
            ./app/build/outputs/bundle/release/app-release.aab
          make_latest: true

