name: StoreScreenshot

on:
  push:
    branches:
      - develop

jobs:
  store-screenshot-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read # for checkout
      actions: write # for upload-artifact
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: record screenshot
        run: |
          ./gradlew recordRoborazziDebug --stacktrace --rerun-tasks
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshots

          path: "**/build/outputs/roborazzi"
          retention-days: 30
