name: UnitTest

on:
  push:
    branches:
      - develop

permissions: { }

jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: read # for clone
      actions: write # for upload-artifact

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          name: screenshot
          workflow: UnitTest.yml
          branch: develop
      - run: ./gradlew recordRoborazziDebug --stacktrace
      - uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: screenshot
          path: |
            **/build/outputs/roborazzi
          retention-days: 30

