name: VRT Test

on:
  pull_request:
    branches:
      - develop

jobs:
  vrt-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run circle ci
        env:
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -H "Circle-Token: ${CIRCLE_TOKEN}" \
          -d "{\"branch\": \"${{ github.head_ref }}\" , \"parameters\": {\"target-branch\": \"${{ github.base_ref }}\", \"pr-number\": ${{ github.event.pull_request.number }} } }" \
          https://circleci.com/api/v2/project/github/SnowDango/sumire/pipeline
    env:
      CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}